services:
  react:
    container_name: react
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - ecommerce_wine

  # nginx_app:
  #   container_name: nginx_app_front
  #   build: ./nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - react-volume:/var/www/html
  #   depends_on:
  #     - react
  #   networks:
  #     - ecommerce_wine

networks:
  ecommerce_wine:
    driver: bridge
   