services:
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - react

volumes:
  react-volume: